debian/system76-power.postrm
debian/system76-power.triggers
src/main.rs

Handle nvidia-fallback.service to prevent nouveau from being loaded, add postrm hook

Improvements for Optimus

---

src/graphics.rs
src/pci.rs

This should fix the side effects of https://github.com/pop-os/system76-dkms/pull/3

[WIP] Remove NVIDIA audio as well as NVIDIA graphics

---

src/daemon.rs
src/hotplug.rs
src/main.rs

Add HotPlugDetect signal that is triggered when an external display is plugged in

Detect display plug-ins

---

Cargo.lock
Cargo.toml
debian/changelog
src/client.rs
src/daemon.rs
src/main.rs

```
$ system76-power graphics switchable
not switchable
$ system76-power graphics switchable
switchable
```

Add GetSwitchable DBUS Method

---

Cargo.lock
Cargo.toml
src/client.rs
src/daemon.rs
src/fan.rs
src/main.rs
src/module.rs

This implements fan control for Thelio. You must test on a fully built Thelio.

Thelio fan control

---

src/client.rs
src/main.rs

Adds a method for `PowerClient` to abstract the common dbus mechanics used in each method.

Simpler power client method calling

---

src/daemon.rs

Allow the initial profile on startup to fail

---

examples/fan.rs
src/fan.rs

This is required to fix issues with fans on massive

Support multiple I/O boards and multiple CPUs

---

src/hotplug.rs

The configuration may need to change because one port _is_ capable of being driven in Intel mode.

Add gaze14 to hotplug detection

---

src/daemon/mod.rs
src/fan.rs

This makes the fan daemon rediscover all usable hwmon devices on each step

Fix #91 - handle hotplugging of Thelio Io

---

src/daemon/mod.rs
src/hotplug.rs

Add addp1 to hotplug daemon

---

src/disks.rs

Skip setting APM for md-raid devices

---

src/fan.rs

Add new fan curve for thelio-major-r1

---

src/daemon/mod.rs
src/daemon/profiles.rs

Persistable brightness

---

README.md

The hybrid mode comes with some caveats worth documenting.

Add notes about graphics modes in README

---

src/client.rs
src/daemon/mod.rs

Queries the current power profile before attempting to change it.
If it is the requested change is the same as the current profile, the system will not attempt to switch.

Only changes power profile, if not current.

---

src/fan.rs

Can be adjusted later as additional information / testing is completed.

Add Thelio Mega

---

Cargo.lock
Cargo.toml
debian/changelog
src/hotplug.rs

0.1.4 - add addw2 and gaze15

---

Cargo.lock
Cargo.toml
debian/changelog
src/daemon/profiles.rs
src/errors.rs

Addresses #166. Rebase and tag after approval
- Balanced is still our really well defined best performance with reasonable noise and heat profile
- Performance kicks it to it's hardware limits, heat and noise be damned
- Battery prevents the fan from coming on, and gives at least 8 hours of battery life even under stress

1.1.5 - Add model-specific power profile for lemp9

---

src/fan.rs

The PR brings a fix for fan unit tests, which previously fails due to wrong variable usage

fixed fan unit tests

---

Cargo.lock
Cargo.toml
debian/changelog
debian/control
examples/hid.rs
src/daemon/mod.rs
src/hid_backlight.rs
src/lib.rs

Will sync color and brightness to the HID LED controllers. Both the lightguide and keyboard
Rebase and tag when approved

Bonw14 keyboard backlight

---

Cargo.lock
Cargo.toml
debian/changelog
src/hid_backlight.rs

1.1.8 - Make HID keyboard backlight update block for events

---

Cargo.lock
Cargo.toml
debian/changelog
src/mux.rs

1.1.10 - Add bonw14 displayport mux support

---

Cargo.lock
Cargo.toml
debian/changelog
src/fan.rs

1.1.11 - Add thelio-major-r2.1 and thelio-mega-r1.1

---

src/client.rs
src/daemon/mod.rs
src/graphics.rs
src/hotplug.rs
src/lib.rs

Add method that checks if the NVIDIA GPU is required for using external displays.

Add DBus method for NVIDIA external display check

---

.github/workflows/CI.yml
examples/hid.rs
rustfmt.toml
src/charge_thresholds.rs
src/client.rs
src/daemon/mod.rs
src/daemon/profiles.rs
src/disks.rs
src/fan.rs
src/graphics.rs
src/hid_backlight.rs
src/hotplug.rs
src/main.rs
src/polkit.rs

i've run `cargo +nightly fmt` and added a github action to check it

enforce and fix formatting

---

src/module.rs

tiny, pointless, and yet very satisfying refactor of `src/module`

refactor src/module

---

src/main.rs

Remove typo in daemon help

---

Cargo.lock
src/fan.rs

Update dependencies and fix building with latest sysfs-class.

Update deps, fix building

---

src/daemon/profiles.rs

Should fix constant freezing experienced on some magnetic drives with faulty support for APM
Closes https://github.com/pop-os/pop/issues/1807

fix: Avoid setting APM parameters for disks due to some disks having faulty support

---

src/acpi_platform.rs
src/daemon.rs
src/daemon/profiles.rs
src/lib.rs

As far as I can tell, only Lenovo laptops support this today.

feat: Use Linux's ACPI Platform Profiles when available

---

Cargo.lock
Cargo.toml
debian/changelog
src/hotplug.rs

Add gaze16-3060-b

---

src/graphics.rs

The NVIDIA driver has two methods to save video memory during suspend:
- Save allocations in an unnamed temporary file
- S0ix-based power management
These are exclusive. Systems using S3 should only use the first, and
systems using S0ix should only use the second.
Requires: pop-os/nvidia-graphics-drivers#128
Ref: pop-os/nvidia-graphics-drivers@de515f69a481
Link: https://download.nvidia.com/XFree86/Linux-x86_64/470.86/README/powermanagement.html#PreserveAllVide719f0

graphics: Preserve video memory during sleep

---

src/hid_backlight.rs

Fixes https://github.com/pop-os/system76-power/issues/267 by taking the potential lack of keyboard backlight color file into account (for products such as lemp10, which have a single-color keyboard backlight.)
There might be a better way to do this; this seemed like the method that would require the least amount of changes to the code.
Not worrying about handling lack of brightness files right now because I'm not aware of any System76 products with keyboards that have LEDs that don't have controllable brightness. If a product doesn't have a keyboard backlight at all, then we already return before we get to this point.

fix: Handle lack of color on some keyboard LEDs

---

src/cpufreq.rs
src/daemon/profiles.rs

Fixes [this Reddit issue](https://www.reddit.com/r/pop_os/comments/t67y6i/weird_fan_behavior_with_oryx_pro_after_upgrades/)

fix: Use powersave on balanced profile

---

src/acpi_platform.rs

fix(daemon): Use "balanced" for acpi-platform balanced setting

---

Cargo.lock
Cargo.toml
debian/changelog
src/fan.rs
src/graphics.rs
src/hotplug/mod.rs

oryp10 has the same GPIO config as oryp9.

hotplug: Add oryp10 detection

---

src/args.rs
src/client.rs

https://github.com/pop-os/system76-power/issues/368

parsing type error fix

---

README.md

The switchable graphics feature is designed for laptops and AIOs. It is not supported on desktops.
Ref: #398

Note that switchable graphics is not for desktops

---

src/hid_backlight.rs
src/lib.rs

This gets colors working more correctly on the bonw15. (Thanks @crawfxrd for the help with the bitmasks.)
Still need to regression test on the bonw14.

hid_backlight: Correct colors on bonw15

---

src/cpufreq.rs

Closes #415 
When the scaling governor is `amd-pstate-epp`, the energy-performance preference at `/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference` should change when the power profile changes. The battery profile sets this to `balance_power`; the balanced profile to "balance_performance"; and the power profile to "performance".

feat: amd-pstate-epp energy_performance_preference config support

---

Cargo.lock
Cargo.toml
debian/changelog
src/graphics.rs
src/hotplug/mod.rs

Only HDMI needs hotplug detection

1.2.7: add gaze20
