pop-os/system76-power

src/main.rs
The daemon flags were always returning false from `is_present()` because they
were called in the wrong subcommand. Moved the logging setup into the match and
shadowed the `matches` variable.
=> Daemon flags fixed.

src/graphics.rs
Adds the detection, but doesn't do anything with it, yet. AMDGPU supports power profile configuration via `/sys/class`, so this is a step towards that.
=> Detect AMD graphics devices

src/client.rs, src/daemon.rs, src/lib.rs
Allows other applications to know which power profile is currently active. The shell extension could use this to accurately detect which profile is active, instead of default to balanced.
=> Add GetProfile dbus method & PowerProfileSwitch dbus signal

examples/fan.rs, src/daemon/mod.rs, src/fan.rs
- Fetches amdgpu temperatures from `amdgpu` hwmon interfaces.
- Fetches NVIDIA temperatures from `nvidia-smi` queries.
Closes #81
=> Read temperatures from GPU(s)

debian/rules, src/mux.rs
This is on the coreboot branch to allow it to install all required features
=> Add darp6 and galp4 to automatic display switching

src/fan.rs
Testing completed with dual XEON Gold 6248 CPUs and quad nvidia RTX 2080 Super Blowers. At idle, the CPU require a fan duty load of 40 to dissipate produced heat. At a 90 duty cycle, the thermal system dissipates CPU heat when fully stressed.
GPUs begin to throttle at 87 degrees. The fan curve increases fan speed to 100% at 85 degrees to limit GPU throttling.
Acoustic results
Test | Decibels | Diff
----- | ------------ | -----
Idle  | 33.45 | -7.2
CPU Stress Result | 39.3 | -5.9
GPU Stress | 55.45 | -2.3
CPU+GPU Stress Result | 55.15 | -2.6
=> Add XEON fan curve and setup thelio-massive-b1 to use it.

Makefile, TESTING.md
* The cmd about 'graphics power state' in TESTING.md is wrong.
* Query discrete graphics power state: system76-power graphics power
* Set discrete graphics power state:  system76-power graphics power [ on | off]
* In Makefile, I suggest that the cmd about the .service file should be added in make [install | uninstall]
=> fix(TESTING.md&&Makefile): The cmd about 'graphics power state' in TESTING.md is wrong.Fix the problem of missing .service file after make install.

Cargo.lock, Cargo.toml, debian/changelog, src/daemon/mod.rs, src/hotplug.rs
Variants are not currently used in coreboot for gaze15, so all models have the same subsystem device ID. Use the ID of the NVIDIA device to determine the variant instead.
=> gaze15: Determine variant by NVIDIA device

src/fan.rs
Combined Major B1, B2, R2 and Mega R1 fan curves into the threadripper3 curve and renamed to hedt. thelio-major-b1 idle noise decreased 2dB to 32.5dB with the original Arctic fans. The hedt curve is also much smoother than the previous corex curve resulting in less fan noise and variation.
=> Improve thelio-major-b1 fan curve

Makefile
Not sure if this made sense at one point, but it doesn't seem to be relevant now. This also doesn't seem to be set when installed from the .deb, so this change should have no effect on the built package.
Fixes https://github.com/pop-os/system76-power/issues/174
=> fix(Makefile): Do not set setuid bit

Cargo.lock, Cargo.toml, src/client.rs, src/daemon/mod.rs
`dbus::ffidisp` is deprecated in favor of `dbus::blocking`, and with the latest release, `dbus::tree` has been moved to a separate crate, and `dbus-crossroads` is meant to replace it. This updates each of these things to the non-deprecated versions.
This also uses dbus-tokio, which makes it possible to have methods that are implemented asynchronously. My immediate goal was to have a sane way to invoke polkit for setting charge thresholds (without blocking the main thread for too long), but this should generally offer more flexibility.
It may be desirable to reimplement all the `Power` methods to be `async`, but this doesn't currently do that.
=> Use dbus 0.9, dbus::blocking, dbus-crossroads, and dbus-tokio

Cargo.lock, Cargo.toml, build.rs, src/hid_backlight.rs, src/lib.rs
Now it builds without warnings, which is always a good thing.
=> Fix build warnings

src/client.rs, src/daemon/mod.rs, src/graphics.rs, src/lib.rs
Add a new DBus method to get the graphics mode a product should use by default.
Only System76 models will default to "hybrid"; Other vendors will default to "nvidia". Some models, such as those without NVIDIA RTD3 power management, should default to "integrated" instead.
=> Add GetDefaultGraphics DBus method

Cargo.lock, Cargo.toml, src/graphics.rs
Use the `supported-gpus.json` file provided by the NVIDIA driver to check if the GPU supports the "runtimepm" feature.
=> Determine default graphics by runtimepm support

data/system76-power.conf, src/graphics.rs
If the NVIDIA device is not on the bus or the drivers are not loaded, assume run-time power management is not supported.
Tested with pop-os/gnome-initial-setup#68.
Fixes: 8959756fee2 ("Determine default graphics by runtimepm support")
=> Report default graphics as integrated if checking RTD3 support fails

src/daemon/profiles.rs
Fixes https://github.com/pop-os/system76-power/issues/210
Observations from running these profiles on an i7 galp5 w/o dGPU:
- performance mode will allow for indefinite turbo boost up to all-core 4.1GHz, but thermally limited
- allowing temps to exceed 95C seems to trigger some cooldown period
- setting pl2 seems to disable or shorten the pl2 boost duration such that the performance profile is useless
- it seems sufficient to not define pl1 or pl2 at all and just let thermal limiting handle everything
=> galp5 profiles and no longer require all profile attributes to be set

Cargo.lock, Cargo.toml, debian/changelog, src/graphics.rs
This requires https://github.com/pop-os/nvidia-graphics-drivers/pull/85 and https://github.com/pop-os/system76-driver/pull/189
=> 1.1.12 - Use hybrid graphics by default for galp5

Cargo.lock, Cargo.toml, debian/changelog, src/fan.rs
Rebase and tag when approved. This sets it up to use the hedt fan curve like thelio-major-b2
=> 1.1.14 - Add thelio-major-b3

src/fan.rs
Tested on Thelio R2 with nvidia 3070 and Mira R1 with nvidia 3080 and 3090 GPUs. Additional intake and exhaust fan speed earlier in the fan curve helped improve performance over longer stress test. Mira's cooling is more advanced and it shows in stress testing. Thelio's GPU watts (performance) were higher in the first 1/2 of the 8 minute stress test but came back to approximately the same results as the previous curve after 8 minutes. 
I did not notice adverse noise from the new ramp. The GPU produces most of the noise (rather than intake and CPU chassis fans). When only stressing the CPU, increased noise wasn't noticeable. Most of the fan noise comes from the last ~25% of potential RPMs which didn't change much with the new fan curve.
=> Improved Standard curve for Thelio and Mira

README.md, src/client.rs, src/main.rs
Switching graphics modes requires a reboot for changes to take effect as it modifies module loading rules that happen during early boot.
=> Document that a reboot is required after switching

README.md
Document the dbus signal used for hotplug detection and link to the shell extension where it's used.
Document how to add hotplug support for new models.
=> Document hotplug support

.github/workflows/coverage.yml
closes #237
the coverage of this repo is low, but that doesn't mean coverage testing isn't useful. it provides a mechanism for ensuring that coverage at least improves over time
=> add coverage workflow

src/cpufreq.rs, src/daemon/profiles.rs, src/lib.rs
- Use powersave (Battery+Balanced) / performance (Performance) only with intel_pstate
- Use conservative (Battery) / schedutil (Balanced) / performance (Performance) with everything else
This will fix older Intel systems that use `intel_cpufreq` (5th gen Core i and older), or something else other than `acpi-cpufreq` (All AMD CPUs).
=> fix: Choose scaling governor more wisely

src/daemon.rs, src/graphics.rs
Set `power/control` for the dGPU based on the graphics mode.
Don't remove the GPU from the bus and rely on RTD3 to put it in D3.
HACK: Defer setting to "auto" for 5 seconds using a thread to avoid a bug that causes the NVIDIA driver to crash and lock up the system. May not always work. (Fixing requires system76/coreboot#98.)
Requires: pop-os/ubuntu-drivers-common#15
Ref: #291
=> Configure runtimepm in sysfs

src/cpufreq.rs
For loops in Rust do not include the last value without adding an equal signal to it.
This can be tested with:
```
watch cat /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor
```
=> Correctly apply changes to all CPU cores

src/daemon/mod.rs, src/graphics.rs
If a device does not support runtime power management, then remove it from the bus when in integrated mode.
Fixes: 1e1599a9dd12 ("daemon: Always enable GPU power")
Resolves: #325
=> Disable dGPU in integrated mode if it doesn't support runtimepm

src/graphics.rs
Fixes running daemon on systems with AMD GPUs and without NVIDIA GPUs.
=> graphics: Assume RTD3 for NVIDIA only

data/com.system76.PowerDaemon.service, debian/system76-power.com.system76.PowerDaemon.service, debian/system76-power.postinst
Installs the service with both names so they're addressable either way.
=> chore: Add system76-power.service as an alias

debian/control
With runtimepm and X configuration implmented, system76-power no longer
relies on behavior from gpu-manager.
gpu-manager should be disabled when using system76-power.
Resolves: #291
Ref: pop-os/ubuntu-drivers-common#20
=> Drop dependency on ubuntu-drivers-common

README.md, src/daemon/profiles.rs
This PR does the following:
- Adds information about Power Profiles to the README based on comments in src/daemon/profile.rs
- Fixes a typo in a comment in that source file
=> Add profile information to README

src/graphics.rs
Desktops should not report as switchable if they have a dGPU. The switchable graphics mechanisms are designed for notebook systems.
The physical selection of ports the *user* chooses when plugging in displays determines whether the iGPU or the dGPU will be used.
- Desktop reports "not switchable" when queried
- gnome-initial-setup does not show the panel about switchable graphics on desktops
- Display output works when plugged into iGPU ports
- Display output works when plugged into dGPU ports
- dGPU can be used as a compute node when displays are plugged into the iGPU ports
=> graphics: Do not report desktops as switchable

src/daemon/mod.rs
Some people are saying that they're having issues after a recent update.  With system76-power being one of these recent updates, this might be the cause. It'd be good if we could get some people with the issues to test this change to see if it's the cause.
- https://www.reddit.com/r/pop_os/comments/zsgw5m/borked_update/
- https://www.reddit.com/r/pop_os/comments/zsawod/did_everyone_get_their_screwed_up_systems_fixed/
- https://www.reddit.com/r/pop_os/comments/zrm6kp/games_freezing_after_latest_system_updates/
- https://www.reddit.com/r/pop_os/comments/zreyvt/pop_os_2204_wired_ethernet_stops_working_after/
- https://www.reddit.com/r/pop_os/comments/zrfxbc/pop_os_2204_has_issues_after_updating_steam_wont/
- https://www.reddit.com/r/pop_os/comments/zrnpzl/hanging_shutdowns/
One person …
=> fix: Disable runtime PM for PCI and I2C devices

src/graphics.rs, src/hotplug/mod.rs
- gaze18: All display ports are connected to the iGPU
- serw13: mDP over USB-C doesn't seem to work on proprietary firmware
=> Add new models

src/graphics.rs, src/hotplug/mod.rs
Aside from wanting hardware support for these systems in 23.04, this PR is also intended to try and get the package to build, since `master_lunar` has currently failed to build (possibly due to the same transient error that the DKMS packages were seeing for a bit.)
=> Update with latest commit (Lunar)

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/disks.rs, src/hid_backlight.rs, src/hotplug/mod.rs
https://github.com/pop-os/system76-power/security/dependabot/1
https://github.com/pop-os/system76-power/security/dependabot/2 (Not a CVE, but this will resolve that dependabot alert too)
=> Update deps to fix CVE-2023-22466

debian/system76-power.postrm, src/graphics.rs
This contains two changes, gated on the bonw15 being detected, that should ensure proper NVIDIA driver suspend operation on bonw15:
- Disable PreserveVideoMemoryAllocations
- Disable NVIDIA hibernate, resume, and suspend services
=> Fixes for NVIDIA suspend on bonw15

src/graphics.rs
Previously if even an empty folder at /usr/share/doc/nvidia-driver-something was found, this function would fail. This should fix the detection of the runtimepm feature.
=> Fix finding supported GPUs file when transitional packages are installed

data/com.system76.PowerDaemon.xml, src/client.rs, src/daemon/mod.rs, src/lib.rs
Print out a error message if the system is not supported. Behaviour before this is a success that looks like the power profile was changed, which is incorrect.
=> Notify in CLI if system is incompatible

src/client.rs
Fixes https://github.com/pop-os/system76-power/issues/424
This patch assumes https://github.com/pop-os/system76-power/commit/27192d28478e42a4d7fa4c21336f9abecb900188 specifically intended to disable Battery power profile on desktops, since desktop computers don't have battery power like laptops.  I don't know what the power profiles do internally, so please let me know if that assumption is incorrect.
Also ran `rustfmt` on the changed area of that file, hoping to keep code style consistent with existing code.
=> Allow using Performance power profile on desktop

src/hid_backlight.rs
Prevents missing `/sys/class/leds/system76_acpi::kbd_backlight/brightness_hw_changed` from causing a crash. Tested on a `lemp9` laptop under NixOS 23.11 with system76-power 1.1.26.
Closes #397
=> Gracefully handle missing brightness_hw_changed

src/charge_thresholds.rs
This should make `system76-power charge-thresholds` report the "Full Charge" profile by default on Open Firmware laptops, instead of reporting a "Custom" profile by default.
=> fix: Match full_charge profile to firmware default values

src/daemon/mod.rs, src/hid_backlight.rs, src/runtime_pm.rs
- Keep Thunderbolt controller active to work around display HPD issue
- Disable runtime power management for TBT xHCI
- Add handling for keyboard LED controls when using system76-dkms
- Check for `color_left` if `color` does not exist
=> bonw15-b: TBT quirks, KBLED handling

Cargo.lock, Cargo.toml, debian/changelog, src/daemon/mod.rs, src/fan.rs, zbus/Cargo.toml
This is to enable thelio-io on ampere desktops
Related to https://github.com/pop-os/system76-driver/pull/300
=> 1.2.1: Allow use of apm_xgene temperatures

src/charge_thresholds.rs
Hello,
This simply checks if device have charge control thresholds ability. In this case, it should works with most of the huawei laptops. Tested on my Matebook and it works.
=> add huawei support for charging thresholds
